######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 26 22:21:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=dbus
QT-=gui
# Input
HEADERS += dbusconnection.h focus.h
SOURCES += dbusconnection.cpp focus.cpp main.cpp
